name: ProjectManager
options:
  bundleIdPrefix: com.aeobrien.projectmanager
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  xcodeVersion: "16.3"
  generateEmptyDirectories: true

packages:
  PMUtilities:
    path: Packages/PMUtilities
  PMDomain:
    path: Packages/PMDomain
  PMData:
    path: Packages/PMData
  PMDesignSystem:
    path: Packages/PMDesignSystem
  PMServices:
    path: Packages/PMServices
  PMFeatures:
    path: Packages/PMFeatures

targets:
  ProjectManager:
    type: application
    platform: macOS
    sources:
      - ProjectManager/Sources
    dependencies:
      - package: PMFeatures
      - package: PMServices
      - package: PMDesignSystem
      - package: PMData
      - package: PMDomain
      - package: PMUtilities
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: ProjectManager/ProjectManager.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.aeobrien.projectmanager
        PRODUCT_NAME: ProjectManager
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Project Manager uses the microphone for voice input to capture ideas and chat with the AI assistant."
    scheme:
      testTargets:
        - ProjectManagerTests
      gatherCoverageData: true

  ProjectManagerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - ProjectManagerTests
    dependencies:
      - target: ProjectManager
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aeobrien.projectmanager.tests
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES

  ProjectManageriOS:
    type: application
    platform: iOS
    sources:
      - path: ProjectManageriOS/Sources
        excludes:
          - "**/Widget/**"
    dependencies:
      - package: PMFeatures
      - package: PMServices
      - package: PMDesignSystem
      - package: PMData
      - package: PMDomain
      - package: PMUtilities
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: ProjectManageriOS/ProjectManageriOS.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.aeobrien.projectmanager.ios
        PRODUCT_NAME: ProjectManager
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Project Manager uses the microphone for voice input to capture ideas and chat with the AI assistant."
    info:
      path: ProjectManageriOS/Info.plist
      properties:
        CFBundleDisplayName: "Project Manager"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~iPad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~iPhone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "Project Manager uses the microphone for voice input to capture ideas and chat with the AI assistant."
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - projectmanager
            CFBundleURLName: "com.aeobrien.projectmanager.ios"

  QuickCaptureWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - ProjectManageriOS/Sources/Widget
    dependencies:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: ProjectManageriOS/QuickCaptureWidgetExtension.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.aeobrien.projectmanager.ios.widget
        PRODUCT_NAME: QuickCaptureWidgetExtension
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Quick Capture"
        INFOPLIST_KEY_NSExtension_NSExtensionPointIdentifier: "com.apple.widgetkit-extension"
